# Generated by Django 4.1.13 on 2024-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_adoption", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
